### ISSUE TITLE
ERROR NotFoundError: Could not find HEAD.

### ISSUE THREAD

**Issue by lida0407** [cocktailpeanut/dalai#109]
Anyone meet this?

dali@das-MacBook-Air /Users % npx dalai alpaca install 7B
mkdir /Users/dali/dalai
{ method: 'install', callparams: [ '7B' ] }
mkdir /Users/dali/dalai/alpaca
try fetching /Users/dali/dalai/alpaca https://github.com/cocktailpeanut/alpaca.cpp.git
ERROR NotFoundError: Could not find HEAD.
    at GitRefManager.resolve (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1962:11)
    at async _currentBranch (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:6603:15)
    at async _fetch (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:7624:24)
    at async Object.fetch (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:9515:12)
    at async Dalai.add (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:272:7)
    at async Dalai.install (/Users/dali/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:226:7) {
  caller: 'git.fetch',
  code: 'NotFoundError',
  data: { what: 'HEAD' }

**Comment by CapsulE07** [comment]
try to git clone  https://github.com/cocktailpeanut/alpaca.cpp.git  to the path , /Users/dali/dalai/alpaca. then check if you could run git fetch in the path. if not, try to update the /etc/hosts until you could execute 'git fetch ' successfully. It  would works

**Comment by AnirudhKanaparthy** [comment]
I am getting the same issue when installing it in windows.
I tried cloning 'alpaca.cpp' into 'dalai' folder. It worked but then it didn't work for
 
`try fetching C:\Users\...\dalai\llama https://github.com/ggerganov/llama.cpp.git`
