### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by MiltonsAngel** [cocktailpeanut/dalai#117]
I keep getting Syntax error when running npx dalai llama install 7B.  My main drive id D:

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\phyls\AppData\Roaming\npm-cache\_npx\24528\node_modules\dalai\node_modules\string-kit\lib\string.js:54:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dalai@0.2.41 postinstall: `node setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dalai@0.2.41 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\phyls\AppData\Roaming\npm-cache\_logs\2023-03-19T11_37_18_902Z-debug.log
Install for [ 'dalai@latest' ] failed with code 1

**Comment by gadzbi123** [comment]
it may be that you need to add the destination of your home directory:
`cd "D:\my\installation\directory`
`npx dalai llama install 7B --home .`
then after installation go run:
`npx dalai serve --home .`
Hope it will help

**Comment by MiltonsAngel** [comment]
@gadzbi123  many thanks for the input.   How can I change the default home folder when I run npx dalai llama install 7B?.  Currently it runs mkdir C:\Users\myuser\llama.  How can I change it to run mkdir D:\dalaillama

**Comment by MiltonsAngel** [comment]
Issue resolved
