### ISSUE TITLE
(windows) Change Directory Error?

### ISSUE THREAD

**Issue by jay5656** [cocktailpeanut/dalai#141]
how do i change the main directory? it just defaults to the C drive when i want to put it on the S drive i have. I assume the solution in the FAQ is for linux

**Comment by zdrummon** [comment]
try typing "npx dalai serve --home s:\YourDevFolder\dalai" to have it install in that folder instead

**Comment by jay5656** [comment]
> try typing "npx dalai serve --home s:\YourDevFolder\dalai" to have it install in that folder instead

ah that worked, i had to have a sub folder, couldnt just put on S, thank you

**Comment by jay5656** [comment]
i keep getting this error, it does not happen on my C drive

C:\Windows\system32>npx dalai serve --home ~S:/DLA
mkdir C:\Windows\system32\~S:\DLA
E Error: ENOENT: no such file or directory, mkdir 'C:\Windows\system32\~S:\DLA'
    at Object.mkdirSync (node:fs:1396:3)
    at new Dalai (C:\Users\jojo\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:44:10)
    at start (C:\Users\jojo\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\web\index.js:8:17)
    at Object.<anonymous> (C:\Users\jojo\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\\Windows\\system32\\~S:\\DLA'
