### ISSUE TITLE
split error when attempting to fetch git package (windows)

### ISSUE THREAD

**Issue by zdrummon** [cocktailpeanut/dalai#144]
![image](https://user-images.githubusercontent.com/3333441/226277378-323fad16-dec7-4ac6-9582-856c9022fbeb.png)

**Comment by TomTonic** [comment]
[E] Pull TypeError: Cannot read properties of null (reading 'split')
    at new GitConfig (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1604:30)
    at GitConfig.from (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1627:12)
    at GitConfigManager.get (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1750:22)
    at async _getConfig (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5397:18)
    at async normalizeAuthorObject (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5407:19)
    at async Object.pull (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:11682:20)
    at async Dalai.add (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:394:7)
    at async Dalai.install (/Users/test/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:346:5) {
  caller: 'git.pull'
}

same problem here
