### ISSUE TITLE
Errors during installation npx dalai alpaca

### ISSUE THREAD

**Issue by spreadzp** [cocktailpeanut/dalai#150]
When I ran the command: "npx dalai alpaca install 7B"
I see the next error trace
```
Need to install the following packages:
  dalai@0.2.50
Ok to proceed? (y) y
mkdir /home/dev/dalai
{ method: 'install', callparams: [ '7B' ] }
mkdir /home/dev/dalai/alpaca
try fetching /home/dev/dalai/alpaca https://github.com/candywrap/alpaca.cpp.git
[E] Pull TypeError: Cannot read properties of null (reading 'split')
    at new GitConfig (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1604:30)
    at GitConfig.from (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1627:12)
    at GitConfigManager.get (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1750:22)
    at async _getConfig (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5397:18)
    at async normalizeAuthorObject (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5407:19)
    at async Object.pull (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:11682:20)
    at async Dalai.add (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:274:7)
    at async Dalai.install (/home/dev/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:227:7) {
  caller: 'git.pull'
}
try cloning /home/dev/dalai/alpaca https://github.com/candywrap/alpaca.cpp.git
next alpaca [AsyncFunction: make]
exec: make in /home/dev/dalai/alpaca
make
exit

```

**Comment by lsempe77** [comment]
same here
