### ISSUE TITLE
Installation - SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by gbajson-area22** [cocktailpeanut/dalai#17]
```
$ npx dalai llama
Need to install the following packages:
  dalai
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'terminal-kit@3.0.0',
npm WARN EBADENGINE   required: { node: '>=16.13.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'seventh@0.8.2',
npm WARN EBADENGINE   required: { node: '>=16.13.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'string-kit@0.17.8',
npm WARN EBADENGINE   required: { node: '>=14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
/home/gbajson/.npm/_npx/3c737cbb02d79cc9/node_modules/string-kit/lib/unicode.js:237
                return emojiWidthLookup.get( code ) ?? 2 ;
                                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gbajson/.npm/_npx/3c737cbb02d79cc9/node_modules/string-kit/lib/string.js:54:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
(⎈|concierge-dev-02:dev-grzeg) (main) gbajson@zauek:~$ npx dalai llama 7B 13B 30B 65B
/home/gbajson/.npm/_npx/3c737cbb02d79cc9/node_modules/string-kit/lib/unicode.js:237
                return emojiWidthLookup.get( code ) ?? 2 ;
                                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gbajson/.npm/_npx/3c737cbb02d79cc9/node_modules/string-kit/lib/string.js:54:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by gbajson-area22** [comment]
```
$ npm --version
8.5.1

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by cacaoMath** [comment]
Your Node.js is v12.22.9. 
I also got the same error, with node.js : v12.22.9
In my case, increasing the node.js version eliminated this error!

**Comment by plankzy** [comment]
I fixed my issues  by using a version of node 12.13.0 LTS (Was using a version of 10) then running 
npm rebuild node-sass
I am using Foundation by Zurb and out of no where I was getting that error and I been working on it a week ago.

**Comment by CHollman82** [comment]
> 

Did you ever solve this? I'm having the same exact problem right now and I tried updating node with nvm to both 12.13.0 LTS as plankzy suggested as well as the newest version listed with "nvm ls available"

Edit:

Nevermind, I figured it out, my problem was this:

https://stackoverflow.com/questions/47017812/nvm-use-does-not-switch-node-versions

nvm does not switch node versions even when it says it does. Had to delete the node.js folder and then run command prompt as admin and use nvm to set version again
