### ISSUE TITLE
Models not getting installed

### ISSUE THREAD

**Issue by samiit** [cocktailpeanut/dalai#193]
I am not able to get the models since the last 12 hours on my Ubuntu machine using 

```
npx dalai llama install 7B
```

Here is the relevant last part of the output:

```
make: Nothing to be done for 'default'.
(base) sam@sam-Aspire-E5-575G:~/dalai/llama$ exit
exit
Download model 7B
checklist.chk 100%[========================================================================================>] done      
params.json 100%[==========================================================================================>] done      
consolidated.00.pth 100%[==================================================================================>] done      
tokenizer_checklist.chk 100%[==============================================================================>] done      
tokenizer.model 100%[======================================================================================>] done      
exec: /home/sam/dalai/venv/bin/python convert-pth-to-ggml.py models/7B/ 1 in /home/sam/dalai/llama
/home/sam/dalai/venv/bin/python convert-pth-to-ggml.py models/7B/ 1
exit
(base) sam@sam-Aspire-E5-575G:~/dalai/llama$ /home/sam/dalai/venv/bin/python convert-pth-to-ggml.py models/7B/ 1
{'dim': 4096, 'multiple_of': 256, 'n_heads': 32, 'n_layers': 32, 'norm_eps': 1e-06, 'vocab_size': -1}
n_parts = 1

Processing part 0

Killed
(base) sam@sam-Aspire-E5-575G:~/dalai/llama$ exit
exit
exec: ./quantize /home/sam/dalai/llama/models/7B/ggml-model-f16.bin /home/sam/dalai/llama/models/7B/ggml-model-q4_0.bin 2 in /home/sam/dalai/llama
./quantize /home/sam/dalai/llama/models/7B/ggml-model-f16.bin /home/sam/dalai/llama/models/7B/ggml-model-q4_0.bin 2
exit
(base) sam@sam-Aspire-E5-575G:~/dalai/llama$ ./quantize /home/sam/dalai/llama/models/7B/ggml-model-f16.bin /home/sam/dalai/llama/models/7B/ggml-model-q4_0.bin 2
llama_model_quantize: loading model from '/home/sam/dalai/llama/models/7B/ggml-model-f16.bin'
llama_model_quantize: failed to open '/home/sam/dalai/llama/models/7B/ggml-model-f16.bin' for reading
main: failed to quantize model from '/home/sam/dalai/llama/models/7B/ggml-model-f16.bin'
(base) sam@sam-Aspire-E5-575G:~/dalai/llama$ exit
exit

```

As you can see, the ggml-model-f16.bin has not been downloaded. Any suggestions what I can do?

Thanks,
Sam

**Comment by genesio-systemlogic** [comment]
I have a similar error with the 13B model in my WSL2 (Ubuntu 20 on Windows 11)


```
genesio@DESKTOP-D9I2CIT:~$ npx dalai llama install 13B
Need to install the following packages:
  dalai@0.2.50
Ok to proceed? (y) y
mkdir /home/genesio/dalai
{ method: 'install', callparams: [ '13B' ] }
mkdir /home/genesio/dalai/llama
try fetching /home/genesio/dalai/llama https://github.com/candywrap/llama.cpp.git
[E] Pull TypeError: Cannot read properties of null (reading 'split')
    at new GitConfig (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1604:30)
    at GitConfig.from (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1627:12)
    at GitConfigManager.get (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:1750:22)
    at async _getConfig (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5397:18)
    at async normalizeAuthorObject (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:5407:19)
    at async Object.pull (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/isomorphic-git/index.cjs:11682:20)
    at async Dalai.add (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:274:7)
    at async Dalai.install (/home/genesio/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:227:7) {
  caller: 'git.pull'
}
try cloning /home/genesio/dalai/llama https://github.com/candywrap/llama.cpp.git
next llama [AsyncFunction: make]
make
exec: make in /home/genesio/dalai/llama
make
exit
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ make
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3   -c ggml.c -o ggml.o
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c utils.cpp -o utils.o
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread main.cpp ggml.o utils.o -o main
\x1b[36mrun ./main -h for help\x1b[0m
g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread quantize.cpp ggml.o utils.o -o quantize
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ exit
exit
Download model 13B
checklist.chk 100%[========================================================================================>] done
params.json 100%[==========================================================================================>] done
consolidated.00.pth 100%[==================================================================================>] done
consolidated.01.pth 100%[==================================================================================>] done
tokenizer_checklist.chk 100%[==============================================================================>] done
tokenizer.model 100%[======================================================================================>] done
exec: /home/genesio/dalai/venv/bin/python convert-pth-to-ggml.py models/13B/ 1 in /home/genesio/dalai/llama
/home/genesio/dalai/venv/bin/python convert-pth-to-ggml.py models/13B/ 1
exit
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ /home/genesio/dalai/venv/bin/python convert-pth-to-ggml.py models/13B/ 1
{'dim': 5120, 'multiple_of': 256, 'n_heads': 40, 'n_layers': 40, 'norm_eps': 1e-06, 'vocab_size': -1}
Namespace(dir_model='models/13B/', ftype=1, vocab_only=0)
n_parts = 2

Processing part 0

Killed
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ exit
exit
exec: ./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin 2 in /home/genesio/dalai/llama
./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin 2
exit
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ ./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin 2
llama_model_quantize: loading model from '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin'
llama_model_quantize: failed to open '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin' for reading
main: failed to quantize model from '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin'
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ exit
exit
exec: ./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1 /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin.1 2 in /home/genesio/dalai/llama
./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1 /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin.1 2
exit
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ ./quantize /home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1 /home/genesio/dalai/llama/models/13B/ggml-model-q4_0.bin.1 2
llama_model_quantize: loading model from '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1'
llama_model_quantize: failed to open '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1' for reading
main: failed to quantize model from '/home/genesio/dalai/llama/models/13B/ggml-model-f16.bin.1'
genesio@DESKTOP-D9I2CIT:~/dalai/llama$ exit
exit
```

**Comment by thomasweiland93** [comment]
The problem occurs in convert-pth-to-ggml.py when pytorch loads the pth files

In my case the error happend because my machine was running out of memory. The Solution for me was the expand the swap file https://bogdancornianu.com/change-swap-size-in-ubuntu/

You could search for the out of memory error message with dmesg.
