### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by scottster44** [cocktailpeanut/dalai#198]
exec: pip3 install --user virtualenv in undefined
innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js
- C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js
- C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js
- C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js
- C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new WindowsPtyAgent (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:40:40)
    at new WindowsTerminal (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:442:32
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:435:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\default.DESKTOP-IUID1JD\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsPtyAgent.js',
    'C:\\Users\\default.DESKTOP-IUID1JD\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsTerminal.js',
    'C:\\Users\\default.DESKTOP-IUID1JD\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\index.js',
    'C:\\Users\\default.DESKTOP-IUID1JD\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\index.js',
    'C:\\Users\\default.DESKTOP-IUID1JD\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\bin\\cli.js'
  ]
}
caught error Error: The module '\\?\C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new WindowsPtyAgent (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:36:36)
    at new WindowsTerminal (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:442:32
    at new Promise (<anonymous>) {
  code: 'ERR_DLOPEN_FAILED'
}
ERROR ReferenceError: ptyProcess is not defined
    at C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:463:9
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:435:12)
    at Dalai.setup (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:337:30)
    at async Dalai.install (C:\Users\default.DESKTOP-IUID1JD\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:7)
    
    Any ideas?

**Comment by Mommotexx** [comment]
First, make sure you followed every step in the windows install documentation
https://github.com/cocktailpeanut/dalai#windows

Here's some tips if that didn't work: 
Check python version. Should be 3.10 or below. 3.11 and above is not supported as I can see in the documentation. 
Check node version, should be 18 or above. npm -v should show version 9.4 or higher. 
If everything is good, you can try to run these commands, and see if it works after running these:

``` 
npm install -g node-pty
pip install ptyprocess
```

Good luck! Tell me if this helps you or not

**Comment by odeno** [comment]
Hi, same problem here..

**Comment by odeno** [comment]
when I type : npm install -g node-pty
It freeze and a new shell open :

Microsoft Windows [version 10.0.19044.2728]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Nicolas\dalai>pip install ptyprocess
Collecting ptyprocess
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Installing collected packages: ptyprocess
Successfully installed ptyprocess-0.7.0
WARNING: You are using pip version 20.2.3; however, version 23.0.1 is available.
You should consider upgrading via the 'c:\users\nicolas\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

C:\Users\Nicolas\dalai>
C:\Users\Nicolas\dalai>npm install -g node-pty
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\node-pty',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\Release\obj\pty\src\win'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\node-pty\\build\\Release\\obj\\pty\\src\\win'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! Les projets sont g�n�r�s individuellement dans cette solution. Pour activer la g�n�ration en parall�le, ajoutez le commutateur "-m".
npm ERR!
npm ERR!   conpty.cc
npm ERR!   path_util.cc
npm ERR!   win_delay_load_hook.cc
npm ERR! C:\\Users\\Nicolas\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\x64\\node.lib : fatal error LNK1127: biblioth�que endommag�e [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\conpty.vcxproj]
npm ERR!   conpty_console_list.cc
npm ERR!   win_delay_load_hook.cc
npm ERR! C:\\Users\\Nicolas\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\x64\\node.lib : fatal error LNK1127: biblioth�que endommag�e [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\conpty_console_list.vcxproj]
npm ERR!   Agent.cc
npm ERR!   AgentCreateDesktop.cc
npm ERR!   ConsoleFont.cc
npm ERR!   ConsoleInput.cc
npm ERR!   ConsoleInputReencoding.cc
npm ERR!   ConsoleLine.cc
npm ERR!   DebugShowInput.cc
npm ERR!   DefaultInputMap.cc
npm ERR!   EventLoop.cc
npm ERR!   InputMap.cc
npm ERR!   LargeConsoleRead.cc
npm ERR!   NamedPipe.cc
npm ERR!   Scraper.cc
npm ERR!   Terminal.cc
npm ERR!   Win32Console.cc
npm ERR!   Win32ConsoleBuffer.cc
npm ERR!   main.cc
npm ERR!   BackgroundDesktop.cc
npm ERR!   Buffer.cc
npm ERR!   DebugClient.cc
npm ERR!   GenRandom.cc
npm ERR!   OwnedHandle.cc
npm ERR!   StringUtil.cc
npm ERR!   WindowsSecurity.cc
npm ERR!   WindowsVersion.cc
npm ERR!   WinptyAssert.cc
npm ERR!   WinptyException.cc
npm ERR!   WinptyVersion.cc
npm ERR!   win_delay_load_hook.cc
npm ERR!   G�n�ration de code en cours
npm ERR!   Previous IPDB not found, fall back to full compilation.
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\deps\winpty\src\agent\Agent.cc(231): warning C4722: 'Agent::~Agent'�: aucun retour du destructeur, fuite de m�moire possible [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
npm ERR!   All 1735 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
npm ERR!   Fin de la g�n�ration du code
npm ERR!   winpty-agent.vcxproj -> C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\Release\\winpty-agent.exe
npm ERR!   AgentLocation.cc
npm ERR!   winpty.cc
npm ERR!   BackgroundDesktop.cc
npm ERR!   Buffer.cc
npm ERR!   DebugClient.cc
npm ERR!   GenRandom.cc
npm ERR!   OwnedHandle.cc
npm ERR!   StringUtil.cc
npm ERR!   WindowsSecurity.cc
npm ERR!   WindowsVersion.cc
npm ERR!   WinptyAssert.cc
npm ERR!   WinptyException.cc
npm ERR!   WinptyVersion.cc
npm ERR!   win_delay_load_hook.cc
npm ERR!      Cr�ation de la biblioth�que C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\Release\winpty.lib et de l'objet C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\Release\winpty.exp
npm ERR!   G�n�ration de code en cours
npm ERR!   Previous IPDB not found, fall back to full compilation.
npm ERR!   All 1044 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
npm ERR!   Fin de la g�n�ration du code
npm ERR!   winpty.vcxproj -> C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\Release\\winpty.dll
npm ERR!   winpty.cc
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(43,55): warning C4311: 'cast de type'�: troncation de pointeur de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(43,55): warning C4302: 'cast de type'�: troncation de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(54): warning C4311: 'cast de type'�: troncation de pointeur de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(54): warning C4302: 'cast de type'�: troncation de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(109,26): warning C4018: '<'�: incompatibilit� signed/unsigned [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(220,110): warning C4311: 'cast de type'�: troncation de pointeur de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(220,110): warning C4302: 'cast de type'�: troncation de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(221,117): warning C4311: 'cast de type'�: troncation de pointeur de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(221,117): warning C4302: 'cast de type'�: troncation de 'HANDLE' � 'int' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(218,25): warning C4533: L'initialisation de 'marshal' est ignor�e par 'goto cleanup'. [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(218,25): message : voir la d�claration de 'marshal' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(238,1): message : voir la d�claration de 'cleanup' [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\src\win\winpty.cc(285,91): warning C4312: 'cast de type'�: la conversion de 'T' en 'HANDLE' d'une taille sup�rieure [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR!           with
npm ERR!           [
npm ERR!               T=int32_t
npm ERR!           ]
npm ERR!   path_util.cc
npm ERR!   win_delay_load_hook.cc
npm ERR! C:\\Users\\Nicolas\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\x64\\node.lib : fatal error LNK1127: biblioth�que endommag�e [C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty\build\pty.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp info find VS using VS2022 (17.5.33516.290) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Nicolas\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\node-pty\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nicolas\\AppData\\Local\\node-gyp\\Cache\\18.15.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Nicolas\\AppData\\Local\\node-gyp\\Cache\\18.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Nicolas\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.15.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\node-pty\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Nicolas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nicolas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Nicolas\AppData\Roaming\npm\node_modules\node-pty
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas\AppData\Local\npm-cache\_logs\2023-03-30T14_35_07_193Z-debug-0.log

**Comment by GolotaRoman91** [comment]
After entering the first request, the connection drops and I get this error:
C:\Users\user>npx dalai serve
mkdir C:\Users\user\dalai
Server running on http://localhost:3000/
> query: { method: 'installed', models: [] }
modelsPath C:\Users\user\dalai\alpaca\models
{ modelFolders: [ '7B' ] }
exists 7B
modelsPath C:\Users\user\dalai\llama\models
{ modelFolders: [] }
> query: {
  seed: -1,
  threads: 4,
  n_predict: 200,
  top_k: 40,
  top_p: 0.9,
  temp: 0.8,
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: false,
  models: [ 'alpaca.7B' ],
  prompt: 'Hi!\n',
  id: 'TS-1680201372748-8977'
}
C:\Users\user\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (C:\Users\user\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:35)
    at Socket.<anonymous> (C:\Users\user\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\user\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\user\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.12.1
