### ISSUE TITLE
ReferenceError: queueContent is not defined

### ISSUE THREAD

**Issue by wiwski** [cocktailpeanut/dalai#220]
Looks like queueContent is not defined on Ubuntu.

```
Instruction
Write the last AI response to complete the dialog.

Dialog
User: Hello, AI. 
AI: Hello! How can I assist you today?
User: How are you ?

Response
AI:" in /home/witold/dalai/alpaca
/media/HDD1/witold/dev/stuff/dalai/dalai/index.js:311
        cb(queueContent)
           ^

ReferenceError: queueContent is not defined
    at Dalai.buffer (/media/HDD1/witold/dev/stuff/dalai/dalai/index.js:311:12)
    at /media/HDD1/witold/dev/stuff/dalai/dalai/index.js:267:16
    at /media/HDD1/witold/dev/stuff/dalai/dalai/index.js:580:13
    at EventEmitter2.fire (/media/HDD1/witold/dev/stuff/dalai/dalai/node_modules/node-pty/lib/eventEmitter2.js:40:22)
    at PipeSocket.<anonymous> (/media/HDD1/witold/dev/stuff/dalai/dalai/node_modules/node-pty/lib/terminal.js:85:61)
    at PipeSocket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

```

**Comment by fabawi** [comment]
Had the same problem but the author solved it shortly after (just update index.js)
