### ISSUE TITLE
Unable to install LLaMa on Windows 11 using Node.js 18.15.0 and npm 9.6.1

### ISSUE THREAD

**Issue by sky10p** [cocktailpeanut/dalai#24]
# Description

I'm trying to install LLaMa on my Windows 11 machine using Node.js 18.15.0 and npm 9.6.1 installed through Volta. However, when I run the command npx dalai llama, I receive the following error:

```
Need to install the following packages:
  dalai@0.0.13
Ok to proceed? (y)
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\sky10\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sky10\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\engine.io-client\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\sky10\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\engine.io-client\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]

```

I have tried running the command with administrator privileges, as well as manually deleting the directory mentioned in the error message, but the issue persists. I have also tried deleting the node_modules folder in my project directory and reinstalling, but that did not solve the problem either.

Can someone please help me resolve this issue so I can successfully install and use LLaMa?

Environment:

* Operating system: Windows 11
* Node.js version: 18.15.0 (installed through Volta)
* npm version: 9.6.1

Thanks in advance for your help!

**Comment by JustAHippo** [comment]
doesn't look like this supports Windows yet! So far, I downloaded the model, have it converted and quantized and can interact with it via the llama cpp but this tool doesn't appear to work with Windows nicely

**Comment by sky10p** [comment]
Alright, I'll keep that in mind. Is it only compatible with Mac, or would it work with Linux too?

**Comment by chuSS** [comment]
i have another error
C:\proj\dalai>npx dalai llama
exec: python3 -m venv C:\proj\dalai\llama.cpp\venv in undefined
C:\proj\dalai\node_modules\node-pty\lib\windowsPtyAgent.js:75
            term = this._ptyNative.startProcess(file, cols, rows, debug, this._generatePipeName(), conptyInheritCursor);
                                   ^
Error: File not found:
    at new WindowsPtyAgent (C:\proj\dalai\node_modules\node-pty\lib\windowsPtyAgent.js:75:36)
    at new WindowsTerminal (C:\proj\dalai\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\proj\dalai\node_modules\node-pty\lib\index.js:28:12)
    at C:\proj\dalai\index.js:200:30
    at new Promise (<anonymous>)
    at Dalai.exec (C:\proj\dalai\index.js:194:12)
    at Dalai.install (C:\proj\dalai\index.js:92:16)
    at Object.<anonymous> (C:\proj\dalai\bin\cli.js:37:17)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.14.1

**Comment by espio999** [comment]
Did you perform with admin privileges?

-->"[Error: EPERM: operation not permitted,"

This message suggests to use "run as administrator", I think.
Run a terminal with "run as administrator" and try again.

**Comment by sky10p** [comment]
> Did you perform with admin privileges?
> 
> -->"[Error: EPERM: operation not permitted,"
> 
> This message suggests to use "run as administrator", I think. Run a terminal with "run as administrator" and try again.

Yes, I did it, but I didn't work, I didn't receive any logs of the command.

**Comment by sky10p** [comment]
I have tried again the command, and it doesn't do anything:

`$ npx dalai llama
Need to install the following packages:
  dalai@0.2.0
Ok to proceed? (y)`

**Comment by CapsulE07** [comment]
I met the same issue as you, and also cant run the project.

**Comment by rearming** [comment]
I have Mac and no effect either. 
<img width="609" alt="Screenshot 2023-03-20 at 20 04 54" src="https://user-images.githubusercontent.com/46020509/226414842-d33a8f5a-6613-4859-8fff-fd5fbca3a7ea.png">

**Comment by scsp85** [comment]
I had figured it out eventually and your mileage may vary. For windows 11 here are some things I did differently.

 (Assuming you following all the instructions)
1. Install the Windows SDK 
2. Run NPM instead of NPX for the first installation command.
3. Using the Microsoft Store install Python 3.10, and make sure the command “python3” is in Path. (It did this for me)

I did a few other things as I tried to figure it out, but I think those three pieces are what fixed it for me.

**Comment by larrybird1** [comment]
same problem, can not install in windows 11

C:\Windows\System32>npx dalai llama install 7B
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) y
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Administrator\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]

**Comment by mafia0047** [comment]
PowerShell 7.4.2
PS C:\Windows\System32> ollama run llama2
pulling manifest
Error: Head "https://dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com/ollama/docker/registry/v2/blobs/sha256/89/8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=66040c77ac1b787c3af820529859349a%!F(MISSING)20240413%!F(MISSING)auto%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20240413T074003Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=8d3f213922cabcb735e8c26efa9a44ec703e999be0cd2c62ed01baeb64b2b90f": dial tcp: lookup dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com: no such host

how to solve this ??
