### ISSUE TITLE
asking install dalai loop and global install error

### ISSUE THREAD

**Issue by ohh25** [cocktailpeanut/dalai#240]
<sub> K:\nodejs>npx dalai alpaca install 13B
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) y</sub>

<sub>K:\nodejs>
K:\nodejs>npx dalai alpaca install 13B
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) n
npm ERR! canceled</sub>

<sub>npm ERR! A complete log of this run can be found in:
npm ERR!     K:\nodejs\node_cache\_logs\2023-03-23T06_46_11_710Z-debug-0.log

<sub>K:\nodejs>npm i -g dalai
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'K:\\nodejs\\node_modules\\dalai',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'K:\nodejs\node_modules\dalai\node_modules\axios\lib'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'K:\\nodejs\\node_modules\\dalai\\node_modules\\axios\\lib'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'K:\\nodejs\\node_modules\\dalai\\node_modules\\node-pty',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'K:\nodejs\node_modules\dalai\node_modules\node-pty\build\deps\winpty\src\Release\obj\winpty\deps\winpty\src'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'K:\\nodejs\\node_modules\\dalai\\node_modules\\node-pty\\build\\deps\\winpty\\src\\Release\\obj\\winpty\\deps\\winpty\\src'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'K:\\nodejs\\node_modules\\dalai\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'K:\nodejs\node_modules\dalai\node_modules\node-pty\build\deps\winpty\src\Release\obj\winpty'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'K:\\nodejs\\node_modules\\dalai\\node_modules\\node-pty\\build\\deps\\winpty\\src\\Release\\obj\\winpty'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path K:\nodejs\node_modules\dalai
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node setup
npm ERR! mkdir C:\Users\Inkkouw\dalai
npm ERR!
npm ERR! downloading self contained python   0% /            downloading self contained python   0% -            downloading self contained python   0% \            downloading self contained python   0% |            downloading self contained python   0% /            downloading self contained python   0% -            downloading self contained python   0% \            downloading self contained python   0% |            downloading self contained python   0% /            downloading self contained python   0% -            downloading self contained python   0% \            downloading self contained python   0% |            downloading self contained python   0% /            Error: Request timed out
npm ERR!     at RedirectableRequest.<anonymous> (K:\nodejs\node_modules\dalai\node_modules\nodejs-file-downloader\makeRequest.js:31:37)
npm ERR!     at RedirectableRequest.emit (node:events:513:28)
npm ERR!     at Timeout.<anonymous> (K:\nodejs\node_modules\dalai\node_modules\follow-redirects\index.js:169:12)
npm ERR!     at listOnTimeout (node:internal/timers:569:17)
npm ERR!     at process.processTimers (node:internal/timers:512:7) {
npm ERR!   code: 'ERR_REQUEST_TIMEDOUT'
npm ERR! }
npm ERR! downloading self contained python 100%[] done      extracting python
npm ERR! Error [Error: ENOENT: no such file or directory, stat 'C:\Users\Inkkouw\dalai\cpython-3.10.9+20230116-x86_64-pc-windows-msvc-shared-install_only.tar.gz'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'stat',
npm ERR!   path: 'C:\\Users\\Inkkouw\\dalai\\cpython-3.10.9+20230116-x86_64-pc-windows-msvc-shared-install_only.tar.gz'
npm ERR! }</sub>

<sub>npm ERR! A complete log of this run can be found in:
npm ERR!     K:\nodejs\node_cache\_logs\2023-03-23T06_46_26_244Z-debug-0.log<html>
<body>
</sub>

**Comment by Desperate666** [comment]
same

**Comment by arindamshivatrip** [comment]
same too

**Comment by vii912** [comment]
same error

**Comment by jinxuan29** [comment]
Ya I got the same issues as well

**Comment by Creative-Ataraxia** [comment]
same, any fix?

**Comment by Creative-Ataraxia** [comment]
same, any fix?

**Comment by shmouelsamares** [comment]
same
