### ISSUE TITLE
Error installing llama 65B

### ISSUE THREAD

**Issue by trevtravtrev** [cocktailpeanut/dalai#249]
I'm on a windows 11 PC. Installing it through the docker instructions. Same error every time.

Had no issues installing llama 7B, 13B, and 30B exactly the same way.

`docker compose run dalai npx dalai llama install 65B
mkdir /root/dalai
{ method: 'install', callparams: [ '65B' ] }
2 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/llama/models' -> '/root/dalai/tmp/models'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/llama/models',
  dest: '/root/dalai/tmp/models'
}
3 [Error: EBUSY: resource busy or locked, rmdir '/root/dalai/llama'] {
  errno: -16,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: '/root/dalai/llama'
}
mkdir /root/dalai/llama
try fetching /root/dalai/llama https://github.com/candywrap/llama.cpp.git
[E] Pull MissingNameError: No name was provided for author in the argument or in the .git/config file.
    at Object.pull (/root/dalai/node_modules/isomorphic-git/index.cjs:11683:24)
    at async Dalai.add (/root/dalai/node_modules/dalai/index.js:394:7)
    at async Dalai.install (/root/dalai/node_modules/dalai/index.js:346:5) {
  caller: 'git.pull',
  code: 'MissingNameError',
  data: { role: 'author' }
}
try cloning /root/dalai/llama https://github.com/candywrap/llama.cpp.git
next llama [AsyncFunction: make]
make
exec: make in /root/dalai/llama
make
exit
root@43edeffeb6a0:~/dalai/llama# make
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:
I CC:       cc (Debian 8.3.0-6) 8.3.0
I CXX:      g++ (Debian 8.3.0-6) 8.3.0

make: Nothing to be done for 'default'.
root@43edeffeb6a0:~/dalai/llama# exit
exit
4 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/tmp/models' -> '/root/dalai/llama/models'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/tmp/models',
  dest: '/root/dalai/llama/models'
}
Download model 65B
Skip file download, it already exists: checklist.chk
Skip file download, it already exists: params.json
Skip file download, it already exists: consolidated.00.pth
node:events:491.pth   0%[                                                                                   ] in 39min
      throw er; // Unhandled 'error' event
      ^

Error: EIO: i/o error, write
Emitted 'error' event on WriteStream instance at:
    at WriteStream.onerror (node:internal/streams/readable:785:14)
    at WriteStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -5,
  code: 'EIO',
  syscall: 'write'
}

Node.js v18.15.0
`

**Comment by christopherorea** [comment]
I do have a problem to in Docker with 7B

`mkdir /root/dalai
{ method: 'install', callparams: [ '7B' ] }
2 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/alpaca/models' -> '/root/dalai/tmp/models'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/alpaca/models',
  dest: '/root/dalai/tmp/models'
}
3 [Error: EBUSY: resource busy or locked, rmdir '/root/dalai/alpaca'] {
  errno: -16,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: '/root/dalai/alpaca'
}
mkdir /root/dalai/alpaca
try fetching /root/dalai/alpaca https://github.com/ItsPi3141/alpaca.cpp
[E] Pull MissingNameError: No name was provided for author in the argument or in the .git/config file.
    at Object.pull (/root/dalai/node_modules/isomorphic-git/index.cjs:11683:24)
    at async Dalai.add (/root/dalai/node_modules/dalai/index.js:394:7)
    at async Dalai.install (/root/dalai/node_modules/dalai/index.js:346:5) {
  caller: 'git.pull',
  code: 'MissingNameError',
  data: { role: 'author' }
}
try cloning /root/dalai/alpaca https://github.com/ItsPi3141/alpaca.cpp
next alpaca [AsyncFunction: make]
exec: make in /root/dalai/alpaca
make
exit
root@9ad5e5455b18:~/dalai/alpaca# make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:  
I CC:       cc (Debian 8.3.0-6) 8.3.0
I CXX:      g++ (Debian 8.3.0-6) 8.3.0

make: Nothing to be done for 'default'.
root@9ad5e5455b18:~/dalai/alpaca# exit
exit
4 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/tmp/models' -> '/root/dalai/alpaca/models'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/tmp/models',
  dest: '/root/dalai/alpaca/models'
}
alpaca.add [ '7B' ]
Skip conversion, file already exists: /root/dalai/alpaca/models/7B/ggml-model-q4_0.bin
`

**Comment by sulzerDE** [comment]
Running 

``` bash
$ sudo docker compose run dalai npx dalai alpaca install 7B
```

solved the problem for me (root privileges are important here)

**Comment by atipton** [comment]
> 

Did you change anything in the Dockerfile?

**Comment by atipton** [comment]
Adding

`RUN apt-get update \
 && apt-get install -y sudo

RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER docker
`

to the Dockerfile then using 

`sudo docker compose run dalai npx dalai alpaca install 7B`

seems to have solved this for me. macOS.
