### ISSUE TITLE
Cannot Complete Request (🌉 TypeError: Cannot read properties of undefined (reading 'toUpperCase'))

### ISSUE THREAD

**Issue by wastella** [cocktailpeanut/dalai#263]
The full error message is, 
  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
  at Readable.push (node:internal/streams/readable:234:10)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at addChunk (node:internal/streams/readable:324:12)
  at Socket.emit (node:events:513:28)
  at Socket.<anonymous> (/usr/local/lib/python3.11/site-packages/javascript/js/bridge.js:278:18)
  at Bridge.onMessage (/usr/local/lib/python3.11/site-packages/javascript/js/bridge.js:226:25)
  at Bridge.call (/usr/local/lib/python3.11/site-packages/javascript/js/bridge.js:136:42)
  at Dalai.request (/usr/local/lib/python3.11/site-packages/javascript/js/node_modules/dalai/index.js:544:18)
  at Dalai.query (/usr/local/lib/python3.11/site-packages/javascript/js/node_modules/dalai/index.js:220:19)
> Model = Model.toUpperCase()
🌉 TypeError: Cannot read properties of undefined (reading 'toUpperCase')

I'm on a Mac, and I'm running the 7b alpaca, I specified the path to the directory, but I dont know what I'm doing wrong.

**Comment by chefbennyj1** [comment]
I've seen this.
Are you creating a node project, and using the constructor?

If so, set the "model" property in the query to "alpaca.7B".
