### ISSUE TITLE
Repeatedly getting "Need to install the following packages: dalai@0.3.1"

### ISSUE THREAD

**Issue by mapleroyal** [cocktailpeanut/dalai#279]
This is a brand new install of vanilla debian.

Installed git, make, build-essential, curl, npm, then ran `npx dalai serve`.

```
user1@debian:~$ npx dalai serve
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) 
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice 
user1@debian:~$ npx dalai serve
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) 
user1@debian:~$ npx dalai serve
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) 
user1@debian:~$
```

**Comment by Lauwny** [comment]
got same issue right now ...

**Comment by BunnySilly** [comment]
encountering same issue

**Comment by jackmandelkorn** [comment]
same issue here

**Comment by ghost** [comment]
encountering same issue :(
Windows 10, node v18.15.0

**Comment by ebruhl** [comment]
Same thing happening to me. I've tried it on about 4 Windows 11 machines and it happens on all of them.

**Comment by Free-Radical** [comment]
Same issue her for 

1. Linux Mint 21 , Node 18.15.0, Python 3.10.9
2. Win 10, WSL2, Ubuntu 22.04 LTS, Node 18.15.0, Python 3.10.6

Errors here, but dont understand-
```
npm info run dalai@0.3.1 postinstall { code: 1, signal: null }
npm verb exit 1
npm verb unfinished npm timer reify 1679954039137
npm verb unfinished npm timer reify:build 1679954041249
npm verb unfinished npm timer build 1679954041250
npm verb unfinished npm timer build:deps 1679954041250
npm verb unfinished npm timer build:run:postinstall 1679954042674
npm verb unfinished npm timer build:run:postinstall:node_modules/dalai 1679954042674
npm verb code 1
```

**Comment by Schnuggler123** [comment]
Same issue here with Linux Mint 21.1, Node v18.15.0, Python 3.10.6
Same issue with a clean Ubuntu 22.10

**Comment by ddwgitlab** [comment]
Had the same problem with Win 11 and MS Visual Studio 2022 Community Edition and node.js manually installed.
Was solved after manually installing python 3.11 from the MS Store.
Hope this helps you.

**Comment by Free-Radical** [comment]
**ok got it to work (on linux mint and WSL2)** 👯  Keep in mind _not ALL models are working  currently_, best model to test install seems to be `alpaca 7B`, so only install that for now

### Try the following 1st- 

1. go to directory **ABOVE THE dalai REPO** (so inside repo do "cd ..")
2.  now run all npx commands (-d or -dd is verbose debugging)
```
$npx -d dalai alpaca install 7B
$npx -d dalai serve 
```

### If that doesn't work do the following-

1. delete local repo and all contents
2. delete ~/dalai dir and all contents (this is where the models and their "drivers" are downloaded and kept)
3. do `git clone `again
4. install `nvm` ensure you use correct node version namely "--lts" 
**directions here**: https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm
5. go to directory **ABOVE THE dalai REPO** (so inside repo do "cd ..")
6. now run all npx commands (-d or -dd is verbose debugging)

```
$npx -d dalai alpaca install 7B
$npx -d dalai serve 
```

PLS LET ME KNOW how far you get.

**Comment by nascherer** [comment]
> Had the same problem with Win 11 and MS Visual Studio 2022 Community Edition and node.js manually installed. Was solved after manually installing python 3.11 from the MS Store. Hope this helps you.

Perfect!!! had the same issue on Win11 H2, Virtual Studio 22, had to download node.js manually but encountered the repeatedly request on installing dalai@0.3.1 -- with python 3.11 installed via store (suppose the direct download works as well ::) install proccess is running atm.

**Comment by ngojclee** [comment]
Hey, I had the same problem with Ubuntu 22.04 and node.js 18 on snap store installed. It was solved after installing node.js from https://github.com/nodesource/distributions. Hope this helps someone!

**Comment by nothingface0** [comment]
> Hey, I had the same problem with Ubuntu 22.04 and node.js 18 on snap store installed. It was solved after installing node.js from [nodesource/distributions](https://github.com/nodesource/distributions). Hope this helps someone!

Can verify that this worked for me too on Ubuntu 22.04. I installed Node.js v19.x as per the instructions in the link posted by @ngojclee. Note that after installation of `node-pty`, the terminal may appear frozen; this is due to downloading `torch`. 

PS: What was breaking before was due to `node-pty` failing to install, with Node 18.x (installed from the snap store). I have no idea why, as I could not really go into depth, nor did I make any sense of the installation logs. 

You can verify what fails on your situation with the `-dd` flags mentioned by @Free-Radical, above.

**Comment by pkgzm** [comment]
I have the same issue too.

I am using Debian testing and I followed the installation instructions which produced no good results.

To get more information messages, I tried to use the installation with npm:

npm -dd install dalai

which produces the following output:

npm verb cli /usr/bin/node /usr/bin/npm
npm info using npm@9.2.0
npm info using node@v18.13.0
npm verb title npm install dalai
npm verb argv "--loglevel" "verbose" "install" "dalai"
npm verb logfile logs-max:10 dir:/home/xxxxxxxx/.npm/_logs/2023-04-14T21_38_29_148Z-
npm verb logfile /home/xxxxxxxx/.npm/_logs/2023-04-14T21_38_29_148Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/dalai 78ms (cache hit)
[...]
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 23ms (cache hit)
npm info run bufferutil@4.0.7 install node_modules/bufferutil node-gyp-build
npm info run node-pty@0.10.1 install node_modules/node-pty node scripts/install.js
npm info run utf-8-validate@5.0.10 install node_modules/utf-8-validate node-gyp-build
npm info run utp-native@2.5.3 install node_modules/utp-native node-gyp-build
npm info run bufferutil@4.0.7 install { code: 0, signal: null }
npm info run utf-8-validate@5.0.10 install { code: 0, signal: null }
npm info run utp-native@2.5.3 install { code: 0, signal: null }
npm info run node-pty@0.10.1 install { code: 0, signal: null }
npm info run dalai@0.3.1 postinstall node_modules/dalai node setup
npm info run node-pty@0.10.1 postinstall node_modules/node-pty node scripts/post-install.js
npm info run node-pty@0.10.1 postinstall { code: 0, signal: null }
npm info run dalai@0.3.1 postinstall { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1091:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid dalai@0.3.1
npm verb cwd /home/xxxxxxxx
npm verb Linux 6.1.0-7-amd64
npm verb node v18.13.0
npm verb npm  v9.2.0
npm ERR! code 1
npm ERR! path /home/xxxxxxxx/node_modules/dalai
npm ERR! command failed
npm ERR! command sh -c node setup
npm ERR! mkdir /home/xxxxxxxx/dalai
npm ERR! exec: apt-get install build-essential python3-venv -y in undefined
npm ERR! apt-get install build-essential python3-venv -y
npm ERR! exit
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ apt-get install build-essential python3-venv -y
E: Impossibile aprire il file di blocco /var/lib/dpkg/lock-frontend - open (13: Permesso negato)
npm ERR! E: Impossibile acquisire il blocco sul frontend dpkg (/var/lib/dpkg/lock-frontend). È necessario essere root.
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ exit
exitERR! 
npm ERR! exec: dnf install make automake gcc gcc-c++ kernel-devel python3-virtualenv -y in undefined
npm ERR! dnf install make automake gcc gcc-c++ kernel-devel python3-virtualenv -y
npm ERR! exit
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ dnf install make automake gcc gcc-c++ kernel-devel python3-virtualenv -y
bash: dnf: comando non trovato
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ exit
exitERR! 
npm ERR! trying with python3
npm ERR! exec: python3 -m venv /home/xxxxxxxx/dalai/venv in undefined
npm ERR! python3 -m venv /home/xxxxxxxx/dalai/venv
npm ERR! exit
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ python3 -m venv /home/xxxxxxxx/dalai/venv
xxxxxxxx@fusion:~/node_modules/dalai$ exit
exitERR! 
npm ERR! { code: true }
npm ERR! trying with python
npm ERR! exec: python -m venv /home/xxxxxxxx/dalai/venv in undefined
npm ERR! python -m venv /home/xxxxxxxx/dalai/venv
npm ERR! exit
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ python -m venv /home/xxxxxxxx/dalai/venv
bash: python: comando non trovato
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ exit
exitERR! 
npm ERR! { code: false }
npm ERR! exec: /home/xxxxxxxx/dalai/venv/bin/pip install --upgrade pip setuptools wheel in undefined
npm ERR! /home/xxxxxxxx/dalai/venv/bin/pip install --upgrade pip setuptools wheel
npm ERR! exit
npm ERR! xxxxxxxx@fusion:~/node_modules/dalai$ /home/xxxxxxxx/dalai/venv/bin/pip install --upgrade pip setuptools wheel
Requirement already satisfied: pip in /home/xxxxxxxx/dalai/venv/lib/python3.11/site-packages (23.0.1)
npm ERR! Requirement already satisfied: setuptools in /home/xxxxxxxx/dalai/venv/lib/python3.11/site-packages (67.6.1)
npm ERR! Requirement already satisfied: wheel in /home/xxxxxxxx/dalai/venv/lib/python3.11/site-packages (0.40.0)

It seems that npm is trying to install already installed packages (torch..., pip, sentencepiece, etc) but it fails because of missing root permission and it is not aware that they are already installed.

I would like to avoid running npm with sudo, which could mess the installation...

**Comment by ahmadkammonah** [comment]
Same Issue here. 

OS: Ubuntu 20.04 (Focal)
node version: v20.1.0
npx version: 9.6.4

The following are the errors I'm getting when running `npm -dd install dalai`

npm ERR! code 1
npm ERR! path /home/kammonah/Desktop/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! make: Entering directory '/home/kammonah/Desktop/node_modules/node-pty/build'
npm ERR!   g++ -o Release/obj.target/pty/src/unix/pty.o ../src/unix/pty.cc '-DNODE_GYP_MODULE_NAME=pty' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/20.1.0/include/node -I/root/.cache/node-gyp/20.1.0/src -I/root/.cache/node-gyp/20.1.0/deps/openssl/config -I/root/.cache/node-gyp/20.1.0/deps/openssl/openssl/include -I/root/.cache/node-gyp/20.1.0/deps/uv/include -I/root/.cache/node-gyp/20.1.0/deps/zlib -I/root/.cache/node-gyp/20.1.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++17 -MMD -MF ./Release/.deps/Release/obj.target/pty/src/unix/pty.o.d.raw   -c
npm ERR! make: Leaving directory '/home/kammonah/Desktop/node_modules/node-pty/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.1.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python3"
npm ERR! gyp verb find Python - executing "/usr/bin/python3" to get version
npm ERR! gyp verb find Python - version is "3.8.10"
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 20.1.0
npm ERR! gyp verb command install [ '20.1.0' ]
npm ERR! gyp verb install input version string "20.1.0"
npm ERR! gyp verb install installing version: 20.1.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 20.1.0
npm ERR! gyp verb build dir attempting to create "build" dir: /home/kammonah/Desktop/node_modules/node-pty/build
npm ERR! gyp verb build dir "build" dir needed to be created? Yes
npm ERR! gyp verb python symlink creating symlink to "/usr/bin/python3" at "/home/kammonah/Desktop/node_modules/node-pty/build/node_gyp_bins/python3"
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /home/kammonah/Desktop/node_modules/node-pty/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /home/kammonah/Desktop/node_modules/node-pty/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /home/kammonah/Desktop/node_modules/node-pty/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/kammonah/Desktop/node_modules/node-pty/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/20.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/20.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/20.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/kammonah/Desktop/node_modules/node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir /root/.cache/node-gyp/20.1.0
npm ERR! gyp verb `which` succeeded for `make` /usr/bin/make
npm ERR! gyp verb bin symlinks adding symlinks (such as Python), at "/home/kammonah/Desktop/node_modules/node-pty/build/node_gyp_bins", to PATH
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: Command not found
npm ERR! make: *** [pty.target.mk:113: Release/obj.target/pty/src/unix/pty.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.4.0-148-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/kammonah/Desktop/node_modules/node-pty
npm ERR! gyp ERR! node -v v20.1.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

Not sure what the solution is. Might try windows.
