### ISSUE TITLE
Manually installed Alpaca 7B does NOT work.

### ISSUE THREAD

**Issue by lanhongken** [cocktailpeanut/dalai#281]
Dear all,

I was following the instruction carefully. The first couple of steps are fine, till I ran

> npx dalai alpaca install 7B

The downloading was stuck at 39%. (I tried several times already.) I then quit the process and downloaded the model manually from Huggingface, and initialized the local service. The following was interface I got. I tried some simple questions, e.g., what time is it now, pressing the GO button --- Saddly, it generates nothing. Any ideas?
![dalai-7b](https://user-images.githubusercontent.com/6933576/227770372-0c730211-5230-4a6e-ac99-866518c433d9.png)
The following was what I got from the cmd prompt.
C:\Users\PC>npx dalai serve
mkdir C:\Users\PC\dalai
Server running on http://localhost:3000/
> query: { method: 'installed', models: [] }
modelsPath C:\Users\PC\dalai\alpaca\models
{ modelFolders: [ '7B' ] }
exists 7B
modelsPath C:\Users\PC\dalai\llama\models
{ modelFolders: [] }
> query: { prompt: '/stop', models: [] }
require log TypeError: Cannot read properties of undefined (reading 'onData')
    at module.exports (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\cmds\stop.js:2:18)
    at Dalai.query (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:207:11)
    at Socket.<anonymous> (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:35)
    at Socket.<anonymous> (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\PC\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0

Thank you!

Cheers,
Hong

**Comment by BresThomas** [comment]
try "clear" in your terminal, then "npx dalai serve".

**Comment by tohrxyz** [comment]
The exact same thing is happening to me.  It crashes after clicking on "Go" button.

**Comment by mapleroyal** [comment]
> Dear all,
> 
> I was following the instruction carefully. The first couple of steps are fine, till I ran
> 
> > npx dalai alpaca install 7B
> 
> The downloading was stuck at 39%. (I tried several times already.) I then quit the process and downloaded the model manually from Huggingface, and initialized the local service. The following was interface I got. I tried some simple questions, e.g., what time is it now, pressing the GO button --- Saddly, it generates nothing. Any ideas? ![dalai-7b](https://user-images.githubusercontent.com/6933576/227770372-0c730211-5230-4a6e-ac99-866518c433d9.png) The following was what I got from the cmd prompt. C:\Users\PC>npx dalai serve mkdir C:\Users\PC\dalai Server running on http://localhost:3000/
> 
> > query: { method: 'installed', models: [] }
> > modelsPath C:\Users\PC\dalai\alpaca\models
> > { modelFolders: [ '7B' ] }
> > exists 7B
> > modelsPath C:\Users\PC\dalai\llama\models
> > { modelFolders: [] }
> > query: { prompt: '/stop', models: [] }
> > require log TypeError: Cannot read properties of undefined (reading 'onData')
> > at module.exports (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\cmds\stop.js:2:18)
> > at Dalai.query (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:207:11)
> > at Socket. (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
> > at Socket.emit (node:events:513:28)
> > at Socket.emitUntyped (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
> > at C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
> > at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
> > C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219
> > let [Core, Model] = req.model.split(".")
> > ^
> 
> TypeError: Cannot read properties of undefined (reading 'split') at Dalai.query (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:35) at Socket. (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20) at Socket.emit (node:events:513:28) at Socket.emitUntyped (C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22) at C:\Users\PC\AppData\Local\npm-cache_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39 at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
> 
> Node.js v18.15.0
> 
> Thank you!
> 
> Cheers, Hong

Do you have folders at

/home/username/dalai/llama/models

or

/home/username/dalai/alpaca/models

Apparently when it's working, people have a full blown install in those directories. Mine don't even HAVE those directories unless I manually create them.

**Comment by mapleroyal** [comment]
FIGURED IT OUT!!!

My last comment got me thinking. Apparently if you have your own models and don't need dalai to download them for you, then `npx dalai serve` does not actually install the rest of the project. Here's what fixes it:

**_Even though you already have the models_**, just run `npx dalai llama install 7B`. It will do some stuff, and then you can cancel it when it starts to download the model. Delete everything except `ggml-vocab.bin` in `/home/user1/llama.cpp/models/` and put your models in there in folders called 7B, 13B, etc. That's it. The whole problem is that whoever made this has completely neglected to even attempt to read the issues lmfao, or to account for the fact that people have our models already.

**Comment by lanhongken** [comment]
> FIGURED IT OUT!!!
> 
> My last comment got me thinking. Apparently if you have your own models and don't need dalai to download them for you, then `npx dalai serve` does not actually install the rest of the project. Here's what fixes it:
> 
> **_Even though you already have the models_**, just run `npx dalai llama install 7B`. It will do some stuff, and then you can cancel it when it starts to download the model. Delete everything except `ggml-vocab.bin` in `/home/user1/llama.cpp/models/` and put your models in there in folders called 7B, 13B, etc. That's it. The whole problem is that whoever made this has completely neglected to even attempt to read the issues lmfao, or to account for the fact that people have our models already.

I am kind of seeing your point: even though I have downloaded the model, I still need to let the installation program finish its job. Your solution works on my laptop, and I am trying to repeat the process on my lab server, let's see what happens. 

Thank you  very much!

Cheers,
Hong

**Comment by AquaB13** [comment]
I have this problem as well, I think its the same problem. i send any question in the web UI and it gives me nothing but a fat Notepad file I am forced to choose an app to open. I tried doing what you said above but unfortunately I'm still in the same boat. does this notepad file say anything about it?

[Joey.txt](https://github.com/cocktailpeanut/dalai/files/11271048/Joey.txt)
