### ISSUE TITLE
Can select "Model", but not "template"

### ISSUE THREAD

**Issue by JourneyJilly** [cocktailpeanut/dalai#326]
I have this running on a hosted server, and have the 7b and 13b models downloaded, but can't get a response seemingly because I cannot select the model.
![bild](https://user-images.githubusercontent.com/74075045/228678482-9916a965-36ff-4a39-a6bf-b239870c34db.png)

Why would the model not be showing up?

here is the output in powershell:

> query: {
  seed: -1,
  threads: 4,
  n_predict: 200,
  top_k: 40,
  top_p: 0.9,
  temp: 0.8,
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: true,
  models: [ 'alpaca.13B', 'alpaca.7B' ],
  prompt: 'test',
  id: 'TS-1680127798439-83081'
}
/root/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (/root/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:219:35)
    at Socket.<anonymous> (/root/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/root/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/typed-events.js:69:22)
    at /root/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.7.0

**Comment by balconychy** [comment]
upgrade socket.io.min.js in /bin/web/public to latest version(v4.6.1) solved this problem. @cocktailpeanut .
