### ISSUE TITLE
No Model selectable - req.model.split(".") ERROR

### ISSUE THREAD

**Issue by FreshImmuc** [cocktailpeanut/dalai#334]
I can't select a model on the web-gui. How do i fix that?
Here is my web gui:
![Screenshot_20230331_125207_Chrome](https://user-images.githubusercontent.com/65733898/229101727-7d6101aa-3938-4699-9794-5f0382db8050.jpg)

And here is the log when i try to submit a prompt:
![Screenshot_20230331_104512_Termius](https://user-images.githubusercontent.com/65733898/229101738-8b596978-7a4f-4f29-bfb3-97fda2da7f16.jpg)

**Comment by Azilone** [comment]
When I follow the instructions to run dailai on docker i can see the model but I have the same error it seems to come from socket.io

**Comment by lucas-strummer** [comment]
I had the same problem, bypassed it by installing a second model.

**Comment by FreshImmuc** [comment]
@lucas-strummer wich models did you install? I installed llama 7B and 13B and it doesnt work...

**Comment by abulka** [comment]
I get this too. I once ran it ok a few weeks ago on another Mac (intel) but now trying on my M1 Mac I get 
```
/Users/andy/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (/Users/andy/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:219:35)
    at Socket.<anonymous> (/Users/andy/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/Users/andy/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/andy/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0
```

Could it be the model isn't downloaded properly? My `~/dalai` directory is not filled with gigabytes of model data. So I ran `npx dalai alpaca install 7B` and now something big is downloading...

**Comment by Hayden2018** [comment]
I have this exact same Error.

**Comment by Mikecodex** [comment]
same error in Windows and in vm linux ubuntu

**Comment by EnguerrandDeclercq** [comment]
I have the same issue. Hardcoded the Core and Model variables in the index.js file to bypass it (line 219). For instance, if you installed llama 7B:

`let [Core, Model] = ['llama', '7B']`

**Comment by Wagner-Peter** [comment]
This is the one that is working for me.
> I have the same issue. Hardcoded the Core and Model variables in the index.js file to bypass it (line 219). For instance, if you installed llama 7B:
> 
> `let [Core, Model] = ['llama', '7B']`

Although, remember to switch "llama" to alpaca if you are using. Worked a charm, thanks man.

**Comment by d-tool** [comment]
If you have installed at least two models, the normal line 219 in index.js works
```
let [Core, Model] = req.model.split(".")
```
If you only have one model installed, you should edit the line to
```
let [Core, Model] = req.models[0].split(".")
```
Hardcoding the models is not a good solution I think and also didn't work for me, as long as I remember correctly

Llama/Alpaca still doesn't work cause it doesn't give me results, it just calculates 'till death. Or..untill I hit the Stop button. But the model problem is fixed. 
It's said that the models are corrupt, which explains the problem of no results (https://github.com/cocktailpeanut/dalai/issues/432) already mentioned by joelduerksen

Also didn't work with other models...

**Comment by xero-q** [comment]
I had one model and none of the solutions worked for me. After hardcoding the model and core it did not show any error when running but it never finished. Now I installed a second model and yet I get the same error. I think the primary cause of error is that the GUI does not receive correctly the installed models so one can't select it, which can be seen in the log in the query, the "models" param is empty.

**Comment by xero-q** [comment]
> @lucas-strummer wich models did you install? I installed llama 7B and 13B and it doesnt work...

@FreshImmuc have you been able to solve this??, I also installed those two same models and I can't put it to work.

**Comment by gavin1818** [comment]
After changing to `let [Core, Model] = req.model[0].split(".")`
I experienced a new issue:
```
    let [Core, Model] = req.model[0].split(".")
                                 ^

TypeError: Cannot read properties of undefined (reading '0')
    at Dalai.query (/Users/xxee/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:219:34)
```
it looks like my model is empty, my first time using the app, and I'm not sure what goes wrong.

Also, my model dropdown is empty in the UI:
<img width="1718" alt="Screen Shot 2023-07-09 at 9 32 21 AM" src="https://github.com/cocktailpeanut/dalai/assets/7432529/2608353f-5cbe-4e16-98fd-2ec8eebc690d">

**Comment by xero-q** [comment]
Same happens to me, no model appears in the UI.

**Comment by LizsDing** [comment]
**Fixed is on my end for Windows.**
It turned out to me that my llama model was not installed (quantize) correctly.
After I applied the fix here, this error was gone for me
https://github.com/cocktailpeanut/dalai/issues/241
