### ISSUE TITLE
Error serving dalai on windows

### ISSUE THREAD

**Issue by lowee1** [cocktailpeanut/dalai#346]
```
>npx dalai serve
mkdir C:\Users\Student\dalai
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1716:21)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at start (C:\Users\Student\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\web\index.js:70:16)
    at Object.<anonymous> (C:\Users\Student\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1760:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}

Node.js v18.13.0

>netstat -ano | findstr :3000

>npx dalai serve
mkdir C:\Users\Student\dalai
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1716:21)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at start (C:\Users\Student\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\web\index.js:70:16)
    at Object.<anonymous> (C:\Users\Student\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1760:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}

Node.js v18.13.0
```

**Comment by enachedaniel19** [comment]
Have you found the solution for this error?

**Comment by EdwardTheLegend** [comment]
I'm really sorry to sat this but I did find a solution back then but I forgot to update this issue and I now don't remember how I fixed it. I'll try and look through my cmd history to work out what happened.

**Comment by enachedaniel19** [comment]
> I'm really sorry to sat this but I did find a solution back then but I forgot to update this issue and I now don't remember how I fixed it. I'll try and look through my cmd history to work out what happened.

**Comment by enachedaniel19** [comment]
> I'm really sorry to sat this but I did find a solution back then but I forgot to update this issue and I now don't remember how I fixed it. I'll try and look through my cmd history to work out what happened.

I managed to find a solution, I started the server on a different port and it worked. Thanks!

**Comment by EdwardTheLegend** [comment]
Ah yeah that was it I think I had a bunch of stuff running locally using lots of ports around the 3000 range.

Anyway guess we can close this. Maybe add a note somewhere for other people?
