### ISSUE TITLE
This error appears when I try to install Alpaca 7B

### ISSUE THREAD

**Issue by Lamaterminator** [cocktailpeanut/dalai#360]
Hi everyone, I use a windows pc to install alpaca 7B,  everytime I type in 'npx dalai alpaca install 7B' this output appears and alpaca doesnt install. Its quiet frustrating because I spent 3 days trying to fix this problem, but nothing works. Does anyone know how to fix this issue?

C:\Users\Elina>npx dalai alpaca install 7b
mkdir C:\Users\Elina\dalai
{ method: 'install', callparams: [ '7b' ] }
extracting pythoncontained python 100%[====================================================================>] done
cleaning up temp files
exec: pip3 install --user virtualenv in undefined
innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js
- C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js
- C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js
- C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js
- C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at new WindowsPtyAgent (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:40:40)
    at new WindowsTerminal (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:563:31
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Elina\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsPtyAgent.js',
    'C:\\Users\\Elina\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsTerminal.js',
    'C:\\Users\\Elina\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\index.js',
    'C:\\Users\\Elina\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\index.js',
    'C:\\Users\\Elina\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\bin\\cli.js'
  ]
}
caught error Error: The module '\\?\C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1361:18)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at new WindowsPtyAgent (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:36:36)
    at new WindowsTerminal (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:563:31
    at new Promise (<anonymous>) {
  code: 'ERR_DLOPEN_FAILED'
}
ERROR TypeError: Cannot read properties of undefined (reading 'kill')
    at C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:589:25
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:556:12)
    at Dalai.setup (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:457:30)
    at async Dalai.install (C:\Users\Elina\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:332:7)

**Comment by odeno** [comment]
Hello there, I have the exact same issue !

**Comment by futureengine-io** [comment]
same

**Comment by MrAnayDongre** [comment]
For alpaca 7B model you can follow the [link](https://github.com/antimatter15/alpaca.cpp).
This is the only direct download I could find.
