### ISSUE TITLE
Cannot read model name and size?

### ISSUE THREAD

**Issue by ulfkemmsies** [cocktailpeanut/dalai#365]
Whenever I attempt to make a query, I get this error. Apparently it cannot read the model name and size, although I have the model 
(Alpaca 7B) selected.

C:\Users\username\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (C:\Users\username\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:35)
    at Socket.<anonymous> (C:\Users\username\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
    at Socket.emit (node:events:512:28)
    at Socket.emitUntyped (C:\Users\username\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\username\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v19.8.1

**Comment by pcrothers91** [comment]
I receive the same error message. Have you found a solution?

**Comment by skyl** [comment]
I was experiencing this at first but I changed the template to `instruction-alpaca` and it hasn't happened again. I just started and don't know if this observation is relevant or not but I found this issue and haven't experienced it since playing with a different template. Maybe I'll report back more later if I learn something ;)
