### ISSUE TITLE
req.model is undefined

### ISSUE THREAD

**Issue by watarungurunnn** [cocktailpeanut/dalai#372]
```
~/node_modules/dalai/index.js:219
    let [Core, Model] = req.model.split(".")
```

```
TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (/Users/watarukawakami/node_modules/dalai/index.js:219:35)
    at Socket.<anonymous> (/Users/watarukawakami/node_modules/dalai/index.js:545:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/Users/watarukawakami/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/watarukawakami/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.7.0
```

**Comment by anaclumos** [comment]
having the same problem

**Comment by watarungurunnn** [comment]
I already fixed in the above PR. plz locally install it!
