### ISSUE TITLE
npx dalai alpaca install 7B not running

### ISSUE THREAD

**Issue by RobinLasserye** [cocktailpeanut/dalai#380]
Hi,

I followed methodically all the steps to make llama works on my PC (Windows 11). 
But I get always the same issue.
I have node v18.14.2, reinstalled Visual Studio 2022 with the correct dev kits. etc

But if I :
> npx dalai alpaca install 7B

mkdir C:\Users\Robin\dalai
{ method: 'install', callparams: [ '7B' ] }
extracting pythoncontained python   0% /
cleaning up temp filesined python 100%[====================================================================>] done      
exec: pip3 install --user virtualenv in undefined
innerError Error: Cannot find module '../build/Debug/conpty.node'
Require stack:
- C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js
- C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js
- C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js
- C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js
- C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\bin\cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new WindowsPtyAgent (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:40:40)
    at new WindowsTerminal (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:563:31
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Robin\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsPtyAgent.js',
    'C:\\Users\\Robin\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\windowsTerminal.js',
    'C:\\Users\\Robin\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\node-pty\\lib\\index.js',
    'C:\\Users\\Robin\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\index.js',
    'C:\\Users\\Robin\\AppData\\Local\\npm-cache\\_npx\\3c737cbb02d79cc9\\node_modules\\dalai\\bin\\cli.js'
  ]
}
caught error Error: The module '\\?\C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new WindowsPtyAgent (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsPtyAgent.js:36:36)
    at new WindowsTerminal (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at Object.spawn (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\node-pty\lib\index.js:28:12)
    at C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:563:31
    at new Promise (<anonymous>) {
  code: 'ERR_DLOPEN_FAILED'
}
ERROR TypeError: Cannot read properties of undefined (reading 'kill')
    at C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:589:25
    at new Promise (<anonymous>)
    at Dalai.exec (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:556:12)
    at Dalai.setup (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:457:30)
    at async Dalai.install (C:\Users\Robin\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:332:7)
    
    
    
I tried to rebuild, install reinstall but I didn't find a solution.

**Comment by Zakirzhan** [comment]
may be you have problems with your hard disk, check do you have need available space?

**Comment by RobinLasserye** [comment]
200Go approximatively, which seems largely sufficient for the 7B model
