### ISSUE TITLE
Don't get response and server stopped by showing Model = Model.toUpperCase() Error.

### ISSUE THREAD

**Issue by gamingjam60** [cocktailpeanut/dalai#397]
When I tried to get a response of a query by typing >Hi
I am getting following error and server stopped

```shell
> query: { method: 'installed', models: [] }
modelsPath /home/baponkar/dalai/alpaca/models
{ modelFolders: [ '7B' ] }
exists 7B
modelsPath /home/baponkar/dalai/llama/models
{ modelFolders: [ '13B', '7B' ] }
> query: {
  seed: -1,
  threads: 4,
  n_predict: 200,
  top_k: 40,
  top_p: 0.9,
  temp: 0.8,
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: true,
  models: [ 'alpaca.7B' ],
  prompt: 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n' +
    '\n' +
    '### Instruction:\n' +
    '>Hi\n' +
    '\n' +
    '### Response:\n',
  id: 'TS-1681552318179-68877'
}
/home/baponkar/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:225
    Model = Model.toUpperCase()
    ^

ReferenceError: Model is not defined
    at Dalai.query (/home/baponkar/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:225:5)
    at Socket.<anonymous> (/home/baponkar/.npm/_npx/3c737cbb02d79cc9/node_modules/dalai/index.js:539:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/home/baponkar/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/baponkar/.npm/_npx/3c737cbb02d79cc9/node_modules/socket.io/dist/socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0

``` 
**How can I resolve this issue?**
Edit : My machine is Ubuntu 22.04 LTS, Python Version-3.9.16

**Comment by JasonXiao89** [comment]
I have got same error.
Mine was solved by change "model: "7B"," to "model: "alpaca.7B",".
