### ISSUE TITLE
EMPTY "MODELS" FOLDER

### ISSUE THREAD

**Issue by khaoula-kplr** [cocktailpeanut/dalai#412]
I have an issue while installing any model ( llama 7B , llama 13B, ....) 
It shows ERROR AxiosError: connect ETIMEDOUT
**As a result i have empty "models" folders and i have no models installed so i can't select any on the web UI**

Did someone had the same error ? 
Thank you.
```
Download model 13B
ERROR AxiosError: connect ETIMEDOUT 198.18.60.12:443
    at AxiosError.from (C:\Users\Mkhao\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\axios\dist\node\axios.cjs:829:14)
    at RedirectableRequest.handleRequestError (C:\Users\Mkhao\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\axios\dist\node\axios.cjs:2975:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (C:\Users\Mkhao\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
}

```

**Comment by bombaglad** [comment]
i have the same exact issue

**Comment by mehdi-lamrani** [comment]
Any update on this, anyone ? 
We are willing to contribute to the project as well, if we can have some guidance here...

**Comment by Nocturna22** [comment]
Download the Files manually and place it like this:
![grafik](https://user-images.githubusercontent.com/46491831/234563102-d21f7d95-407f-49f0-9e25-dd8610191db4.png)



Try these: [alpaca7B](https://huggingface.co/guy1267/alpaca7B/tree/main), [alpaca13B](https://huggingface.co/guy1267/alpaca13B/tree/main)
