### ISSUE TITLE
docker compose run dalai npx dalai alpaca install 7B not working !

### ISSUE THREAD

**Issue by elaarabi** [cocktailpeanut/dalai#442]
I am having a hard time installing using docker.
Docker version 20.10.18 under Ubuntu 20.04.
Any solutions please ?

`mkdir /root/dalai
{ method: 'install', callparams: [ '7B' ] }
2 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/alpaca/models' -> '/root/dalai/tmp/models'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/alpaca/models',
  dest: '/root/dalai/tmp/models'
}
3 [Error: EBUSY: resource busy or locked, rmdir '/root/dalai/alpaca'] {
  errno: -16,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: '/root/dalai/alpaca'
}
mkdir /root/dalai/alpaca
try fetching /root/dalai/alpaca https://github.com/ItsPi3141/alpaca.cpp
[E] Pull MissingNameError: No name was provided for author in the argument or in the .git/config file.
    at Object.pull (/root/dalai/node_modules/isomorphic-git/index.cjs:11683:24)
    at async Dalai.add (/root/dalai/node_modules/dalai/index.js:394:7)
    at async Dalai.install (/root/dalai/node_modules/dalai/index.js:346:5) {
  caller: 'git.pull',
  code: 'MissingNameError',
  data: { role: 'author' }
}
try cloning /root/dalai/alpaca https://github.com/ItsPi3141/alpaca.cpp
next alpaca [AsyncFunction: make]
exec: make in /root/dalai/alpaca
make
exit
root@a373257fb6fe:~/dalai/alpaca# make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx -mavx2 -mfma -mf16c -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:
I CC:       cc (Debian 8.3.0-6) 8.3.0
I CXX:      g++ (Debian 8.3.0-6) 8.3.0

make: Nothing to be done for 'default'.
root@a373257fb6fe:~/dalai/alpaca# exit
exit
4 [Error: EXDEV: cross-device link not permitted, rename '/root/dalai/tmp/models' -> '/root/dalai/alpaca/models'] {       
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/root/dalai/tmp/models',
  dest: '/root/dalai/alpaca/models'
}`

**Comment by FrancescaRagazzi** [comment]
Same problem in Ubuntu 22.10

**Comment by mirek190** [comment]
Why you even using it .... this is so obsolete project. ...
Go to llama.cpp or koboldccp
