### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by Rudraksh418** [cocktailpeanut/dalai#458]
![image](https://github.com/cocktailpeanut/dalai/assets/122471529/e16d397f-1ac4-41cd-b03d-029945b6c397)

**Comment by shakram02** [comment]
same thing here

**Comment by me20b054** [comment]
Yeah same. Any possible solution for this?

**Comment by Caro-Tabar** [comment]
Same problem on Ubuntu. 

Node.js version
18.16.1

Python3 version 
Python 3.10.6

**Comment by afif-malghani** [comment]
Ran into the same issue,

investigated further by running `npx --loglevel verbose dalai llama install 7B`,

the log showed error in installation of the package `node-pty`.

tried installing `node-pty` with `npm install node-pty`

failed on command `sh -c node-gyp rebuild`

[edit]
Environment info:
Node: 18.16.1
npm: 9.5.1
python: 3.10.6
pip: 22.0.2
OS: Ubuntu 22.04 LTS
Linux: 5.19.0

**Comment by ewwwgiddings** [comment]
Here's the complete error for me:
```Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\egiddings\AppData\Roaming\npm-cache\_npx\23276\node_modules\dalai\node_modules\node-pty
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.10.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by martin19** [comment]
doesn't work. this code is just scary.

**Comment by junxian428** [comment]
mine window works but maybe model is just 7B ![image](https://github.com/cocktailpeanut/dalai/assets/58724748/e0452aa8-b7e3-4132-a4cf-c57e5c9b131b)
