### ISSUE TITLE
main: failed to quantize model

### ISSUE THREAD

**Issue by grigio** [cocktailpeanut/dalai#64]
```
downloading consolidated.00.pth 100%[======================================================================>] done      
Skip file download, it already exists: tokenizer_checklist.chk
Skip file download, it already exists: tokenizer.model
exec: /home/grigio/llama.cpp/venv/bin/python convert-pth-to-ggml.py models/7B/ 1 in /home/grigio/llama.cpp
/home/grigio/llama.cpp/venv/bin/python convert-pth-to-ggml.py models/7B/ 1
exit
[grigio@hua llama.cpp]$ /home/grigio/llama.cpp/venv/bin/python convert-pth-to-ggml.py models/7B/ 1
{'dim': 4096, 'multiple_of': 256, 'n_heads': 32, 'n_layers': 32, 'norm_eps': 1e-06, 'vocab_size': 32000}
n_parts =  1
Processing part  0
Traceback (most recent call last):
  File "/home/grigio/llama.cpp/convert-pth-to-ggml.py", line 88, in <module>
    model = torch.load(fname_model, map_location="cpu")
  File "/home/grigio/llama.cpp/venv/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/grigio/llama.cpp/venv/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/grigio/llama.cpp/venv/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/7B//consolidated.00.pth'
[grigio@hua llama.cpp]$ exit

```

**Comment by grigio** [comment]
I fixed downloading `consolidated.00.pth` with https://github.com/shawwn/llama-dl
