### ISSUE TITLE
I deployed it on gcp and have an external IP. Issue with rendering respons

### ISSUE THREAD

**Issue by allthingssecurity** [cocktailpeanut/dalai#71]
The web page shows up but when I ask a question. I get no response. On looking into the chrome console I see the errors
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at sha256 ((index):201:49)
    at i.<anonymous> ((index):229:24)
    at L.emit (socket.io.min.js:6:7123)
    at i.value (socket.io.min.js:6:34942)
    at i.value (socket.io.min.js:6:34646)
    at i.value (socket.io.min.js:6:34300)
    at L.emit (socket.io.min.js:6:7123)
    at socket.io.min.js:6:41258

Not sure what is the issue.

**Comment by valentinvieriu** [comment]
see https://github.com/cocktailpeanut/dalai/issues/34
It's related with https.
