### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by amosayomide05** [cocktailpeanut/dalai#72]
```
SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dalai/node_modules/string-kit/lib/string.js:54:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm WARN notsup Unsupported engine for terminal-kit@3.0.0: wanted: {"node":">=16.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: terminal-kit@3.0.0
npm WARN notsup Unsupported engine for isomorphic-git@1.22.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: isomorphic-git@1.22.0
npm WARN notsup Unsupported engine for seventh@0.8.2: wanted: {"node":">=16.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: seventh@0.8.2
npm WARN notsup Unsupported engine for string-kit@0.17.8: wanted: {"node":">=14.15.0"}
(current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: string-kit@0.17.8
npm WARN notsup Unsupported engine for pngjs@6.0.0: wanted: {"node":">=12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pngjs@6.0.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dalai@0.2.4 postinstall: `node ./bin/cli setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dalai@0.2.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-17T06_35_57_667Z-debug.log
ayomide@ayomideml:~$
```

I am using node version 19.0.0

**Comment by santhoshshivanna** [comment]
```
npm http fetch GET 200 https://registry.npmjs.org/emoji-regex 51ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/wrap-ansi 53ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 43ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/dalai/-/dalai-0.2.40.tgz 734ms (cache miss)
npm info run node-pty@0.10.1 install node_modules/dalai/node_modules/node-pty node scripts/install.js
npm info run node-pty@0.10.1 install { code: 0, signal: null }
npm info run dalai@0.2.40 postinstall node_modules/dalai node setup
npm info run node-pty@0.10.1 postinstall node_modules/dalai/node_modules/node-pty node scripts/post-install.js
npm info run node-pty@0.10.1 postinstall { code: 0, signal: null }
npm info run dalai@0.2.40 postinstall { code: null, signal: 'SIGINT' }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/home/username/.nvm/versions/node/v19.8.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:512:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm verb pkgid dalai@0.2.40
npm verb cwd /home/username/llama
npm verb Linux 5.19.0-35-generic
npm verb node v19.8.1
npm verb npm  v9.5.1
npm ERR! path /home/username/.nvm/versions/node/v19.8.1/lib/node_modules/dalai
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c node setup
npm ERR! mkdir /home/username/dalai
npm ERR! exec: apt-get install build-essential python3-venv -y in undefined
npm ERR! apt-get install build-essential python3-venv -y
npm ERR! exit

```

command tried `npm install -g dalai --verbose` using node v19.8.1
it seems to be stuck during post-install

**Comment by amosayomide05** [comment]
Try #91
